apiVersion: v1
kind: Secret
metadata:
  name: task-db-secret
type: Opaque
stringData:
  POSTGRES_DB: taskdb
  POSTGRES_USER: CHANGE_ME
  POSTGRES_PASSWORD: CHANGE_ME
  DATABASE_URL: postgresql+psycopg://CHANGE_ME:CHANGE_ME@postgres:5432/taskdb

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: CHANGE_ME
  POSTGRES_PASSWORD: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: CHANGE_ME
  KC_BOOTSTRAP_ADMIN_PASSWORD: CHANGE_ME